### ISSUE TITLE
rm_toolkit

### ISSUE THREAD

**Issue by claudiobosticco** [martonmiklos/robomow_usb_adapter#1]
Hello, thanks for the usb adapter, may I ask if you know where I could find the rm_toolkit ?

**Comment by martonmiklos** [comment]
-

**Comment by claudiobosticco** [comment]
Thank you very much!

**Comment by martonmiklos** [comment]
I exchanged the link in the meantime, I posted a newer toolkit link first accidentally ;).

**Comment by claudiobosticco** [comment]
downloaded, thank you

**Comment by claudiobosticco** [comment]
Actually I need it for a RM400, hope it will work ;-)

**Comment by martonmiklos** [comment]
I tested it with an RM-510 which has identical board to the RM400.

What's the plan? Repair or hacking?

**Comment by martonmiklos** [comment]
Also note that the pin 4 and 5 (TX/RX)  is swapped on the board, just I was lazy pig fixing it in the design yet.

**Comment by claudiobosticco** [comment]
Actually main problem is that the display goes crazy, and shows random changing characters. 
If I disconnect the batteries for a while, when I reconnect them it works, then after a while it starts with random characters and gets worse with time. So the first goal is to have a way to access its menus without having to first disconnect batteries. Then if I manage to repair it would be nice.

**Comment by martonmiklos** [comment]
Best of luck to the repair!

**Comment by martonmiklos** [comment]
> Actually I need it for a RM400, hope it will work ;-)

FYI: I tested it yesterday w. an RM400 board and it works OK.
